// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Output {
    #[prost(message, repeated, tag = "1")]
    pub data: ::prost::alloc::vec::Vec<TradeData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeData {
    #[prost(string, required, tag = "1")]
    pub block_date: ::prost::alloc::string::String,
    #[prost(int64, required, tag = "2")]
    pub block_time: i64,
    #[prost(uint64, required, tag = "3")]
    pub block_slot: u64,
    #[prost(string, required, tag = "4")]
    pub tx_id: ::prost::alloc::string::String,
    #[prost(string, required, tag = "6")]
    pub pool_address: ::prost::alloc::string::String,
    #[prost(string, required, tag = "7")]
    pub amm_config: ::prost::alloc::string::String,
    #[prost(string, required, tag = "15")]
    pub instruction_type: ::prost::alloc::string::String,
    #[prost(string, required, tag = "18")]
    pub dapp: ::prost::alloc::string::String,
    #[prost(uint64, required, tag = "19")]
    pub trade_fee_rate: u64,
    #[prost(uint64, required, tag = "20")]
    pub protocol_fee_rate: u64,
    #[prost(uint64, required, tag = "21")]
    pub fund_fee_rate: u64,
    #[prost(uint64, required, tag = "22")]
    pub param: u64,
    #[prost(uint64, required, tag = "23")]
    pub value: u64,
    #[prost(uint64, required, tag = "24")]
    pub create_pool_fee: u64,
}
