// This file is generated by build.rs
pub mod sf {
    pub mod solana {
        pub mod raydium_amm {
            pub mod v1 {
                // Include the generated code directly from the src/pb directory
                include!("sf.solana.raydium_amm.v1.rs");
            }
        }
    }
} 