use std::collections::HashMap;

pub fn create_programs_map() -> HashMap<&'static str, &'static str> {
    let program_data = vec![
        (
            "frakt",
            vec![
                "A66HabVL3DzNzeJgcHYtRRNW1ZRMKwBfrdSR4kLsZ9DJ"
                ,"regNrR9XpXkg6VCZXEyTwCGVETwKpZMtQxYx3zResJh"
                ,"raffyhEJMx59iDx778Y9gdaVcP2XDeusPcPBxwr3qAH"
                ,"4tdmkuY6EStxbS6Y8s5ueznL3VPMSugrvQuDeAHGZhSt"
            ]
        ),
        (
            "squads",
            vec![
                "SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf"
                ,"SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu"
                ,"SMPL5bz5ERMdweouWrXtk3jmb6FnjZkWf7pHDsE6Zwz"
                ,"SMPLbiNbsa19gf9jz8x9uHSvSn9VLFJB38dGy46kqJ7"
                ,"SMPLKTQhrgo22hFCVq2VGX1KAktTWjeizkhrdB1eauK"
                ,"SMPLVC8MxZ5Bf5EfF7PaMiTCxoBAcmkbM2vkrvMK8ho"
            ]
        ),
        (
            "orca",
            vec![
                "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
               ,"9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP"
               ,"DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1"
            ]
        ),
        (
            "helium",
            vec![
                "circAbx64bbsscPbQzZAUvuXpHqrCe6fLMzc2uKXz9g"
               ,"credMBJhYFzfn7NxBMdU4aUqFggAjgztaCcv2Fo6fPT"
               ,"hemjuPXBpNvggtaUnN1MwT3wrdhttKEfosTcc2P9Pg8"
               ,"hdaoVTCqhfHHo75XdAMxBKdUqvq1i5bF23sisBqVgGR"
               ,"1azyuavdMyvsivtNxPoz6SucD18eDHeXzFCUPq5XU7w"
               ,"1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h"
               ,"treaf4wWBBty3fHdyBpo35Mz84M8k3heKXmjmi9vFt5"
               ,"hvsrNC3NKbcryqDs2DocYHZ9yPKEVzdSjQG6RVtK1s8"
               ,"iotEVVZLEywoTn1QdwNPddxPWszn3zFhEot3MfL9fns"
               ,"mb1eu7TzEc71KxDpsmsKoucSSuuoGLv1drys1oP2jh6"
           ]
        ),
        (
            "openbook",
            vec![
                "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"
                ,"opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb"
            ]
        ),
        (
            "saber",
            vec![
                "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"
            ]
        ),
        (
            "xnftbackpack",
            vec![
                "xnft5aaToUM4UFETUQfj7NUDUBdvYHTVhNFThEYTm55"
            ]
        ),
        (
            "stake_pool",
            vec![
                "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
            ]
        ),
        (
            "spl_governance",
            vec![
                "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
            ]
        ),
        (
            "lifinity",
            vec![
                "EewxydAPCCVuNEyrVN68PuSYdQ7wKn27V9Gjeoi8dy3S"
                ,"2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c"
            ]
        ),
        (
            "libreplex",
            vec![
                "LibrQsXf9V1DmTtJLkEghoaF1kjJcAzWiEGoJn8mz7p"
                ,"rndbQFmFfiQ4tTG9QPhfJeq1J9fLCSBMAPj3EbLQ7Co"
                ,"inscokhJarcjaEs59QbQ7hYjrKz25LEPRfCbP8EmdUp"
                ,"78deTr7qycJ6498vSd3pNMhdCKKWxMipniitVHQcM8RM"
                ,"ListjawGEdhxuAErSyYwcTEGWQswFoi6FScnGG1RKSB"
                ,"G9whLiLT9nSkxwWzWvbiKKrTL6yWxvzh2UXqNht5VXqV"
                ,"9SXDHUdtfvBGT3H2uPCNEkxmWREoqdeS1qdBudLDD6KX"
                ,"Leg1xVbrpq5gY6mprak3Ud4q4mBwcJi5C9ZruYjWv7n"
            ]
        ),
        (
            "meteora",
            vec![
                "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB"
               ,"24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi" 
               ,"LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"
            ]
        ),
        (
            "fluxbeam",
            vec![
                "FLUXubRmkEi2q6K3Y9kBPg9248ggaZVsoSFhtJHSrm1X"
            ]
        ),
        (
            "hadeswap",
            vec![
                "hadeK9DLv9eA7ya5KCTqSvSvRZeJC3JgD5a9Y3CNbvu"
            ]
        ),
        (
            "exchange_art",
            vec![
                "exAuvFHqXXbiLrM4ce9m1icwuSyXytRnfBkajukDFuB" 
               ,"exofLDXJoFji4Qyf9jSAH59J4pp82UT5pmGgR6iT24Z" 
               ,"AmK5g2XcyptVLCFESBCJqoSfwV3znGoVYQnqEnaAZKWn" 
               ,"EXBuYPNgBUXMTsjCbezENRUtFQzjUNZxvPGTd11Pznk5" 
           ]
        ),
        (
            "alldomains",
            vec![
                "TLDHkysf5pCnKsVA4gXpNvmy7psXLPEu4LAdDJthT9S" 
                ,"ALTNSZ46uaAUU7XUV6awvdorLGqAsPwa9shm7h4uP2FK" 
                ,"TLDM2itbqSCEGnCBEF5ExqbePWQGJpkAW2t5noVqHu9" 
                ,"NH3uX6FtVE2fNREAioP7hm5RaozotZxeL6khU1EHx51" 
                ,"APooLSMjJV9kkqEWX2QvDyStkdPesVugMALsMvPLbsnx" 
            ]
        ),
        (
            "metaplex",
            vec![
                "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s",
                "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk",
                "cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ",
                "cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ",
                "CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR",
                "Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g",
                "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY",
                "hyDQ4Nz1eYyegS6JfenyKwKzYxRsCWCriYSAjtzP4Vg",
                "trifMWutwBxkSuatmpPVnEe7NoE3BJKgjVi8sSyoXWX",
            ],
        ),
        (
            "mango_markets",
            vec![
                "4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg",
                "mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68",
                "GqTPL6qRf5aUuqscLh8Rg2HTxPUXfhhAXDptTLhp1t2J",
                "JD3bq9hGdy38PuWQ4h2YJpELmHVGPPfFSuFkpzAd9zfu",
                "5fNfvyp5czQVX77yoACa3JJVEhdRaWjPuazuWgjhTqEH",
            ],
        ),
    ];

    let mut program_map: HashMap<&str, &str> = HashMap::new();

    for (program_name, program_ids) in program_data {
        for program_id in program_ids {
            program_map.insert(program_id, program_name);
        }
    }

    program_map
}
