use std::collections::HashMap;

pub fn create_programs_map() -> HashMap<&'static str, &'static str> {
    let program_data = vec![
        (
            "metaplex",
            vec![
                "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s",
                "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk",
                "cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ",
                "cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ",
                "CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR",
                "Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g",
                "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY",
                "hyDQ4Nz1eYyegS6JfenyKwKzYxRsCWCriYSAjtzP4Vg",
                "trifMWutwBxkSuatmpPVnEe7NoE3BJKgjVi8sSyoXWX",
            ],
        ),
        (
            "staratlas",
            vec![
                "traderDnaR5w6Tcoi3NFm53i48FTDNbGjBSZwWXDRrg",
                "FLEET1qqzpexyaDpqb2DGsSzE2sDCizewCg9WjrA6DBW",
                "ATLocKpzDbTokxgvnLew3d7drZkEzLzDpzwgrgWKDbmc",
                "STAKEr4Bh8sbBMoAVmTDBRqouPzgdocVrvtjmhJhd65",
                "FACTNmq2FhA2QNTnGM2aWJH3i7zT3cND5CgvjYTjyVYe",
                "TESTWCwvEv2idx6eZVQrFFdvEJqGHfVA1soApk2NFKQ",
                "gateVwTnKyFrE8nxUUgfzoZTPKgJQZUbLsEidpG4Dp2",
                "Lock7kBijGCQLEFAmXcengzXKA88iDNQPriQ7TbgeyG",
                "snapNQkxsiqDWdbNfz8KVB7e3NPzLwtHHA6WV8kKgUc",
                "SAGEqqFewepDHH6hMDcmWy7yjHPpyKLDnRXKb3Ki8e6",
                "Craftf1EGzEoPFJ1rpaTSQG1F6hhRRBAf4gRo9hdSZjR",
                "Cargo8a1e6NkGyrjy4BQEW4ASGKs9KSyDyUrXMfpJoiH",
                "pprofELXjL5Kck7Jn5hCpwAL82DpTkSYBENzahVtbc9",
                "pv1ttom8tbyh83C1AVh6QH2naGRdVQUVt3HY1Yst5sv",
                "pFACSRuobDmvfMKq1bAzwj27t6d2GJhSCHb1VcfnRmq",
                "APR1MEny25pKupwn72oVqMH4qpDouArsX8zX4VwwfoXD",
            ],
        ),
        (
            "frakt",
            vec![
                "A66HabVL3DzNzeJgcHYtRRNW1ZRMKwBfrdSR4kLsZ9DJ",
                "regNrR9XpXkg6VCZXEyTwCGVETwKpZMtQxYx3zResJh",
                "raffyhEJMx59iDx778Y9gdaVcP2XDeusPcPBxwr3qAH",
                "4tdmkuY6EStxbS6Y8s5ueznL3VPMSugrvQuDeAHGZhSt",
            ],
        ),
        (
            "squads",
            vec![
                "SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf",
                "SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu",
                "SMPL5bz5ERMdweouWrXtk3jmb6FnjZkWf7pHDsE6Zwz",
                "SMPLbiNbsa19gf9jz8x9uHSvSn9VLFJB38dGy46kqJ7",
                "SMPLKTQhrgo22hFCVq2VGX1KAktTWjeizkhrdB1eauK",
                "SMPLVC8MxZ5Bf5EfF7PaMiTCxoBAcmkbM2vkrvMK8ho",
            ],
        ),
        (
            "orca",
            vec![
                "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc",
                "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP",
                "DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1",
            ],
        ),
        (
            "phoenix",
            vec!["PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY"],
        ),
        (
            "helium",
            vec![
                "circAbx64bbsscPbQzZAUvuXpHqrCe6fLMzc2uKXz9g",
                "credMBJhYFzfn7NxBMdU4aUqFggAjgztaCcv2Fo6fPT",
                "hemjuPXBpNvggtaUnN1MwT3wrdhttKEfosTcc2P9Pg8",
                "hdaoVTCqhfHHo75XdAMxBKdUqvq1i5bF23sisBqVgGR",
                "1azyuavdMyvsivtNxPoz6SucD18eDHeXzFCUPq5XU7w",
                "1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h",
                "treaf4wWBBty3fHdyBpo35Mz84M8k3heKXmjmi9vFt5",
                "hvsrNC3NKbcryqDs2DocYHZ9yPKEVzdSjQG6RVtK1s8",
                "iotEVVZLEywoTn1QdwNPddxPWszn3zFhEot3MfL9fns",
                "mb1eu7TzEc71KxDpsmsKoucSSuuoGLv1drys1oP2jh6",
            ],
        ),
        (
            "jupiter",
            vec![
                "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
                "JUP5cHjnnCx2DppVsufsLrXs8EBZeEZzGtEK9Gdz6ow",
                "JUP5pEAZeHdHrLxh5UCwAbpjGwYKKoquCpda2hfP4u8",
                "JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB",
                "JUP3c2Uh3WA4Ng34tw6kPd2G4C5BB21Xo36Je1s32Ph",
                "JUP2jxvXaqu7NQY1GmNF4m1vodw12LVXYxbFL2uJvfo",
                "JUP6i4ozu5ydDCnLiMogSckDPpbtr7BJ4FtzYWkb5Rk",
                "PERPHjGBqRHArX4DySjwM6UJHiR3sWAatqfdBS2qQJu",
                "jupoNjAxXgZ4rjzxzPMP4oxduvQsQtZzyknqvzYNrNu",
                "DCA265Vj8a9CEuX1eb1LWRnDT7uK6q1xMipnNyatn23M",
            ],
        ),
        (
            "raydium",
            vec![
                "RVKd61ztZW9GUwhRbbLoYVRE5Xf1B2tVscKqwZqXgEr",
                "27haf8L6oxUeXrHrgEgsexjSY5hbVUWEmvv9Nyxg8vQv",
                "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
                "5quBtoiQqxF9Jv6KYKctB59NT3gtJD2Y65kdnB1Uev3h",
                "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK",
                "routeUGWgWzqBWFcrCfv8tritsqukccJPu3q5GPP3xS",
                "EhhTKczWMGQt46ynNeRX1WfeagwwJd7ufHvCDjRxjo5Q",
                "9KEPoZmtHUrBbhWN1v1KWLMkkvwY6WLtAVUCPRtRjP4z",
                "FarmqiPv5eAj3j1GMdMCMUGXqPUvmquZtMy86QH6rzhG",
                "9HzJyW1qZsEiSfMUf6L2jo3CcTKAyBmSyKdwQeYisHrC",
            ],
        ),
        (
            "solend",
            vec!["So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo"],
        ),
        (
            "zeta",
            vec![
                "ZETAxsqBRek56DhiGXrn75yj2NHU3aYUnxvHXpkf3aD",
                "zDEXqXEG7gAyxb1Kg9mK5fPnUdENCGKzWrM21RMdWRq",
            ],
        ),
        (
            "mango_markets",
            vec![
                "4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg",
                "mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68",
                "GqTPL6qRf5aUuqscLh8Rg2HTxPUXfhhAXDptTLhp1t2J",
                "JD3bq9hGdy38PuWQ4h2YJpELmHVGPPfFSuFkpzAd9zfu",
                "5fNfvyp5czQVX77yoACa3JJVEhdRaWjPuazuWgjhTqEH",
            ],
        ),
        (
            "drift",
            vec![
                "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH",
                "DraWMeQX9LfzQQSYoeBwHAgM5JcqFkgrX7GbTfjzVMVL",
            ],
        ),
        (
            "magiceden",
            vec![
                "M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K",
                "MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8",
                "mmm3XBJg5gk8XJxEKBvdgptZz6SgK4tXvn36sodowMc",
                "CMX5tvuWs2rBUL3vqVWiARfcDoCKjdeSinCsZdxJmYoF",
                "CMY8R8yghKfFnHKCWjzrArUpYH4PbJ56aWBr4kCP4DMk",
                "CMZYPASGWeTz7RNGHaRJfCq2XQ5pYK6nDvVQxzkH51zb",
                "ocp4vWUzA2z2XMYJ3QhM9vWdyoyoQwAFJhRdVTbvo9E",
                "M3mxk5W2tt27WGT7THox7PmgRDp4m6NEhL5xvxrBfS1",
            ],
        ),
        (
            "marginfi",
            vec![
                "LipsxuAkFkwa4RKNzn51wAsW7Dedzt1RNHMkTkDEZUW",
                "MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA",
            ],
        ),
        (
            "marinade",
            vec![
                "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD",
                "tokdh9ZbWPxkFzqsKqeAwLDk6J6a8NBZtQanVuuENxa",
                "tovt1VkTE2T4caWoeFP6a2xSFoew5mNpd7FWidyyMuk",
                "va12L6Z9fa5aGJ7gxtJuQZ928nySAk5UetjcGPve3Nu",
                "LigadctxNRkZied3WuhX525vUhDkuhXNK5DyeijeDnh",
                "MR2LqxoSbw831bNy68utpu5n4YqBH3AzDmddkgk9LQv",
                "dstK1PDHNoKN9MdmftRzsEbXP5T1FTBiQBm1Ee3meVd",
                "VoteMBhDCqGLRgYpp9o7DGyq81KNmwjXQRAHStjtJsS",
                "mnspJQyF1KdDEs5c6YJPocYdY1esBgVQFufM2dY9oDk",
            ],
        ),
        (
            "openbook",
            vec![
                "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX",
                "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb",
            ],
        ),
        ("robox", vec!["rbxKHT1j2EnkfvVgANWFXdcV5Sm8EkdZLLDjJ5R1Lwa"]),
        ("saber", vec!["SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"]),
        (
            "wormhole",
            vec![
                "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth",
                "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb",
                "WnFt12ZrnzZrFZkt2xsNsaNWoQribnuQ5B5FrDbwDhD",
            ],
        ),
        (
            "mayan_swap",
            vec!["8LPjGDbxhW4G2Q8S6FvdvUdfGWssgtqmvsc63bwNFA7E"],
        ),
        (
            "debridge",
            vec![
                "dst5MGcFPoBeREFAA5E3tU5ij8m5uVYwkzkSAbsLbNo",
                "src5qyZHqTqecJV4aY6Cb6zDZLMDzrDKKezs22MPHr4",
                "DEbrdGj3HsRsAzx6uH4MKyREKxVAfBydijLUF3ygsFfh",
                "DeSetTwWhjZq6Pz9Kfdo1KoS5NqtsM6G8ERbX4SSCSft",
            ],
        ),
        (
            "allbridge",
            vec!["BrdgN2RPzEMWF96ZbnnJaUtQDQx7VRXYaHHbYCBvceWB"],
        ),
        (
            "xnftbackpack",
            vec!["xnft5aaToUM4UFETUQfj7NUDUBdvYHTVhNFThEYTm55"],
        ),
        (
            "tensor",
            vec![
                "TSWAPaqyCSx2KABk68Shruf4rp7CxcNi8hAsbdwmHbN",
                "TCMPhJdwDryooaGtiocG1u3xcYbRpiJzb283XfCZsDp",
                "TL1ST2iRBzuGTqLn1KXnGdSnEow62BzPnGiqyRXhWtW",
            ],
        ),
        (
            "stake_pool",
            vec!["SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"],
        ),
        (
            "spl_governance",
            vec!["GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"],
        ),
        (
            "sharky",
            vec!["SHARKobtfF1bHhxD2eqftjHBdVSCbKo9JtgK71FhELP"],
        ),
        (
            "light_protocol",
            vec!["2c54pLrGpQdGxJWUAoME6CReBrtDbsx5Tqx4nLZZo6av"],
        ),
        (
            "lifinity",
            vec![
                "EewxydAPCCVuNEyrVN68PuSYdQ7wKn27V9Gjeoi8dy3S",
                "2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c",
            ],
        ),
        (
            "libreplex",
            vec![
                "LibrQsXf9V1DmTtJLkEghoaF1kjJcAzWiEGoJn8mz7p",
                "rndbQFmFfiQ4tTG9QPhfJeq1J9fLCSBMAPj3EbLQ7Co",
                "inscokhJarcjaEs59QbQ7hYjrKz25LEPRfCbP8EmdUp",
                "78deTr7qycJ6498vSd3pNMhdCKKWxMipniitVHQcM8RM",
                "ListjawGEdhxuAErSyYwcTEGWQswFoi6FScnGG1RKSB",
                "G9whLiLT9nSkxwWzWvbiKKrTL6yWxvzh2UXqNht5VXqV",
                "9SXDHUdtfvBGT3H2uPCNEkxmWREoqdeS1qdBudLDD6KX",
                "Leg1xVbrpq5gY6mprak3Ud4q4mBwcJi5C9ZruYjWv7n",
            ],
        ),
        (
            "meteora",
            vec![
                "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB",
                "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi",
            ],
        ),
        (
            "fluxbeam",
            vec!["FLUXubRmkEi2q6K3Y9kBPg9248ggaZVsoSFhtJHSrm1X"],
        ),
        (
            "hubble",
            vec![
                "HubbLeXBb7qyLHt3x7gvYaRrxQmmgExb7fCJgDqFuB6T",
                "6LtLpnUFNByNXLyCoK9wA2MykKAmQNZKBdY8s47dehDc",
                "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",
            ],
        ),
        (
            "hadeswap",
            vec!["hadeK9DLv9eA7ya5KCTqSvSvRZeJC3JgD5a9Y3CNbvu"],
        ),
        (
            "exchange_art",
            vec![
                "exAuvFHqXXbiLrM4ce9m1icwuSyXytRnfBkajukDFuB",
                "exofLDXJoFji4Qyf9jSAH59J4pp82UT5pmGgR6iT24Z",
                "AmK5g2XcyptVLCFESBCJqoSfwV3znGoVYQnqEnaAZKWn",
                "EXBuYPNgBUXMTsjCbezENRUtFQzjUNZxvPGTd11Pznk5",
            ],
        ),
        (
            "elusiv_privacy",
            vec!["4CgyHKuP6yi1vbmcdsArngEKcETR4nZupqYEMk2hEoQd"],
        ),
        (
            "alldomains",
            vec![
                "TLDHkysf5pCnKsVA4gXpNvmy7psXLPEu4LAdDJthT9S",
                "ALTNSZ46uaAUU7XUV6awvdorLGqAsPwa9shm7h4uP2FK",
                "TLDM2itbqSCEGnCBEF5ExqbePWQGJpkAW2t5noVqHu9",
                "NH3uX6FtVE2fNREAioP7hm5RaozotZxeL6khU1EHx51",
                "APooLSMjJV9kkqEWX2QvDyStkdPesVugMALsMvPLbsnx",
            ],
        ),
        (
            "native_stake",
            vec!["Stake11111111111111111111111111111111111111"],
        ),
    ];

    let mut program_map: HashMap<&str, &str> = HashMap::new();

    for (program_name, program_ids) in program_data {
        for program_id in program_ids {
            program_map.insert(program_id, program_name);
        }
    }

    program_map
}
